In [1]:
from pandas import DataFrame, Series
import pandas as pd
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [2]:
df_pay = pd.read_csv('home-credit-default-risk/installments_payments.csv', na_values=['','XNA','XAP'])
df_POS = pd.read_csv('home-credit-default-risk/POS_CASH_balance.csv', na_values=['','XNA','XAP'])
train_main = pd.read_csv('home-credit-default-risk/application_train.csv', na_values=['','XNA','XAP'])

In [3]:
df_pay_filled = df_pay
df_pay_filled['AMT_PAYMENT'].fillna(0, inplace=True)
df_pay_filled['DAYS_ENTRY_PAYMENT'].fillna(1, inplace=True)

df_POS.dropna(inplace=True)

In [4]:
(df_pay_filled.isnull().sum() / len(df_pay_filled)*100).sort_values(ascending = False)

AMT_PAYMENT               0.0
AMT_INSTALMENT            0.0
DAYS_ENTRY_PAYMENT        0.0
DAYS_INSTALMENT           0.0
NUM_INSTALMENT_NUMBER     0.0
NUM_INSTALMENT_VERSION    0.0
SK_ID_CURR                0.0
SK_ID_PREV                0.0
dtype: float64

In [5]:
((df_POS.isnull().sum() / len(df_POS))*100).sort_values(ascending = False)

SK_DPD_DEF               0.0
SK_DPD                   0.0
NAME_CONTRACT_STATUS     0.0
CNT_INSTALMENT_FUTURE    0.0
CNT_INSTALMENT           0.0
MONTHS_BALANCE           0.0
SK_ID_CURR               0.0
SK_ID_PREV               0.0
dtype: float64

## POS Summary

In [6]:
df_POS.sort_values(by='SK_DPD', ascending=False)[:12]

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
7631038,1326802,188881,-1,4.0,0.0,Active,4231,0
8724938,1326802,188881,-2,4.0,0.0,Active,4200,0
8724934,1326802,188881,-3,4.0,0.0,Active,4172,0
7630846,1326802,188881,-4,4.0,0.0,Active,4141,0
8725575,1326802,188881,-5,4.0,0.0,Active,4110,0
9898783,2343790,449462,-1,24.0,0.0,Active,4108,0
8724641,1326802,188881,-6,4.0,0.0,Active,4080,0
9841828,2343790,449462,-2,24.0,0.0,Active,4078,0
7948162,1575102,313054,-2,10.0,0.0,Demand,4050,0
9995874,2076069,318331,-1,16.0,0.0,Active,4050,0
7631030,1326802,188881,-7,4.0,0.0,Active,4049,0
9898633,2343790,449462,-3,24.0,0.0,Active,4047,0

In [7]:
df_POS.sort_values(by='SK_DPD')[:10]

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0
6558407,2659432,452786,-2,12.0,5.0,Active,0,0
6558408,2357778,276820,-1,10.0,0.0,Completed,0,0
6558409,1190239,356122,-1,10.0,4.0,Active,0,0
6558410,2083387,186871,-4,10.0,0.0,Completed,0,0
6558411,2467429,332140,-5,12.0,5.0,Active,0,0
6558412,2772428,446987,-7,12.0,6.0,Active,0,0
6558406,2703013,321024,-1,10.0,4.0,Active,0,0
6558413,1447013,373591,-6,12.0,7.0,Active,0,0
6558415,2408613,407411,-4,12.0,6.0,Active,0,0

In [8]:
counter = lambda x: x.ne(0).sum()

In [9]:
df_POS_group = df_POS.groupby('SK_ID_CURR')['SK_DPD'].agg([counter, 'count', 'max', 'min', 'mean'])
print (df_POS_group)

            <lambda>  count   max  min        mean
SK_ID_CURR
100001             1      9     7    0    0.777778
100002             0     19     0    0    0.000000
100003             0     28     0    0    0.000000
100004             0      4     0    0    0.000000
100005             0     10     0    0    0.000000
100006             0     20     0    0    0.000000
100007             0     66     0    0    0.000000
100008            43     83  1294    0  339.060241
100009             0     64     0    0    0.000000
100010             0     11     0    0    0.000000
100011            35     75   952    0  205.666667
100012             0     46     0    0    0.000000
100013             2     36    18    0    0.944444
100014             0     16     0    0    0.000000
100015             1     11    13    0    1.181818
100016             0     67     0    0    0.000000
100017             0     31     0    0    0.000000
100018             0     25     0    0    0.000000
100019             0      8     0    0    0.000000
100020             0     14     0    0    0.000000
100021             0     27     0    0    0.000000
100022             0      7     0    0    0.000000
100023             0     29     0    0    0.000000
100025             0     40     0    0    0.000000
100026             0     11     0    0    0.000000
100027             0     23     0    0    0.000000
100028             0     31     0    0    0.000000
100029             0      6     0    0    0.000000
100030             0     14     0    0    0.000000
100032             0      7     0    0    0.000000
...              ...    ...   ...  ...         ...
456225             0     57     0    0    0.000000
456226             0      5     0    0    0.000000
456227             0     55     0    0    0.000000
456228             0     74     0    0    0.000000
456230             0     26     0    0    0.000000
456231             0     29     0    0    0.000000
456232             0     28     0    0    0.000000
456233             0     10     0    0    0.000000
456234             1     14    16    0    1.142857
456235             0     35     0    0    0.000000
456236             0     36     0    0    0.000000
456237             0     42     0    0    0.000000
456238             0      5     0    0    0.000000
456239             0     11     0    0    0.000000
456240             0     53     0    0    0.000000
456241             0     43     0    0    0.000000
456242             0     32     0    0    0.000000
456243             0     22     0    0    0.000000
456244             2     80     4    0    0.087500
456245             0     20     0    0    0.000000
456246             0      7     0    0    0.000000
456247             0     27     0    0    0.000000
456248             4     43    20    0    1.767442
456249             0     13     0    0    0.000000
456250             0     30     0    0    0.000000
456251             0      8     0    0    0.000000
456252             0      7     0    0    0.000000
456253             1     17     5    0    0.294118
456254             0     20     0    0    0.000000
456255             1     71     5    0    0.070423

[337224 rows x 5 columns]

In [10]:
df_POS_group['percentage_no_DPD']= 1-(df_POS_group['<lambda>']/df_POS_group['count'])

In [11]:
print(df_POS_group.sort_values(by='percentage_no_DPD',ascending=False)[:10])

            <lambda>  count  max  min  mean  percentage_no_DPD
SK_ID_CURR
278242             0     28    0    0   0.0                1.0
295113             0      1    0    0   0.0                1.0
295099             0     24    0    0   0.0                1.0
295100             0     40    0    0   0.0                1.0
295101             0     22    0    0   0.0                1.0
414861             0     24    0    0   0.0                1.0
414860             0     22    0    0   0.0                1.0
414859             0     21    0    0   0.0                1.0
414857             0     12    0    0   0.0                1.0
414856             0     18    0    0   0.0                1.0

In [12]:
df_POS_group['percentage_no_DPD'].value_counts().iloc[:10]

1.000000    274240
0.923077      1306
0.916667      1103
0.909091       975
0.875000       897
0.900000       872
0.947368       863
0.944444       847
0.960000       846
0.928571       838
Name: percentage_no_DPD, dtype: int64

## Pay Summary

In [13]:
def greater(series):
    if series >= 1:
        return 1
    else:
        return 0

In [14]:
df_pay_filled['DPD'] = df_pay_filled['DAYS_ENTRY_PAYMENT']-df_pay_filled['DAYS_INSTALMENT']
df_pay_filled['DPD_Count'] = df_pay_filled['DPD'].map(greater)
#if PAID/NOT = 1, then they have not paid that loan, 0 means they have made a payment
df_pay_filled['NOT_PAID'] = df_pay_filled['DAYS_ENTRY_PAYMENT'].map(greater)
df_pay_filled['UNDER_PAY'] = df_pay_filled['AMT_INSTALMENT']-df_pay_filled['AMT_PAYMENT']

mask1 = df_pay_filled['DAYS_ENTRY_PAYMENT'] != 1
mask2 = df_pay_filled['AMT_INSTALMENT'] > df_pay_filled['AMT_PAYMENT']

df_pay_filled['UNDER_PAY_COUNT']=df_pay_filled[mask1&mask2]['UNDER_PAY'] > 0

In [15]:
df_pay_filled.sort_values(by='SK_ID_CURR')[:10]

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,DPD,DPD_Count,NOT_PAID,UNDER_PAY,UNDER_PAY_COUNT
3458712,1369693,100001,1.0,3,-1649.0,-1660.0,3951.000,3951.000,-11.0,0,0,0.0,NaN
3435373,1851984,100001,1.0,4,-2856.0,-2856.0,3980.925,3980.925,0.0,0,0,0.0,NaN
2624024,1369693,100001,2.0,4,-1619.0,-1628.0,17397.900,17397.900,-9.0,0,0,0.0,NaN
1761012,1851984,100001,1.0,2,-2916.0,-2916.0,3982.050,3982.050,0.0,0,0,0.0,NaN
3774071,1851984,100001,1.0,3,-2886.0,-2875.0,3982.050,3982.050,11.0,1,0,0.0,NaN
1478621,1369693,100001,1.0,1,-1709.0,-1715.0,3951.000,3951.000,-6.0,0,0,0.0,NaN
2568722,1369693,100001,1.0,2,-1679.0,-1715.0,3951.000,3951.000,-36.0,0,0,0.0,NaN
2163032,1038818,100002,1.0,2,-535.0,-562.0,9251.775,9251.775,-27.0,0,0,0.0,NaN
504426,1038818,100002,1.0,12,-235.0,-250.0,9251.775,9251.775,-15.0,0,0,0.0,NaN
699804,1038818,100002,1.0,13,-205.0,-224.0,9251.775,9251.775,-19.0,0,0,0.0,NaN

In [16]:
df_pay_filled.sort_values(by='UNDER_PAY_COUNT',ascending=False)[:10]

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,DPD,DPD_Count,NOT_PAID,UNDER_PAY,UNDER_PAY_COUNT
4,2714724,167756,1.0,2,-1383.0,-1366.0,2165.040,2160.585,17.0,1,0,4.455,True
9065429,1252118,338955,1.0,12,-613.0,-642.0,9827.055,385.200,-29.0,0,0,9441.855,True
9065461,2821390,352196,1.0,10,-572.0,-511.0,6666.840,14.400,61.0,1,0,6652.440,True
9065456,1476661,345872,1.0,7,-1291.0,-1274.0,8128.980,0.360,17.0,1,0,8128.620,True
9065455,1666935,309380,1.0,21,-381.0,-405.0,13799.565,2738.700,-24.0,0,0,11060.865,True
9065451,2383335,315906,1.0,7,-1742.0,-1734.0,4823.055,4817.385,8.0,1,0,5.670,True
9065446,1977877,372854,1.0,2,-1989.0,-1979.0,5816.880,5813.415,10.0,1,0,3.465,True
9065444,1865406,319450,1.0,10,-1944.0,-1926.0,5037.525,4753.575,18.0,1,0,283.950,True
9065430,2408435,318089,0.0,18,-902.0,-894.0,561.735,222.660,8.0,1,0,339.075,True
9065426,2641684,343934,0.0,6,-839.0,-839.0,4897.305,4896.900,0.0,0,0,0.405,True

In [17]:
df_pay_filled[df_pay_filled['NOT_PAID']==1]['UNDER_PAY_COUNT'].sum()

0

In [18]:
df_pay_filled['DPD_min'] = df_pay_filled['DPD']
df_pay_filled['DPD_avg'] = df_pay_filled['DPD']

In [19]:
df_pay_filled['UNDER_PAY_COUNT'].sum()

1295493

In [20]:
df_pay_group = df_pay_filled.groupby('SK_ID_CURR').agg({'NUM_INSTALMENT_NUMBER':'count','NOT_PAID':'sum', 'DPD':'max','DPD_min':'min','DPD_avg':'mean', 
                                                        'DPD_Count':'sum',
                                                        'AMT_INSTALMENT':'sum', 'AMT_PAYMENT':'sum', 'UNDER_PAY_COUNT':'sum'})

In [21]:
#some could have underpaid on some and overpaid on others, how should we represent this?
df_pay_group.sort_values(by='NOT_PAID',ascending=False)[:10]

,NUM_INSTALMENT_NUMBER,NOT_PAID,DPD,DPD_min,DPD_avg,DPD_Count,AMT_INSTALMENT,AMT_PAYMENT,UNDER_PAY_COUNT
SK_ID_CURR,,,,,,,,,
380139,114,57,1725.0,-30.0,438.447368,80,176653.260,150263.370,16
145820,90,45,1354.0,-28.0,341.655556,60,112989.330,110392.020,4
345102,94,43,1282.0,-30.0,294.765957,68,334718.460,311759.190,5
344624,79,38,1152.0,-11.0,291.569620,61,419272.650,412742.970,5
418486,204,35,1043.0,-30.0,87.044118,42,2663257.815,945596.340,8
405063,34,34,2909.0,1905.0,2407.352941,34,70.560,0.000,0
371681,121,25,1060.0,-96.0,137.157025,25,2158083.900,1735365.555,0
300212,92,23,883.0,-30.0,136.467391,34,4560405.030,2937665.430,8
103793,83,23,729.0,-52.0,99.144578,31,2803732.965,1564780.635,13
112813,89,19,497.0,-30.0,52.921348,22,2813225.490,1522621.215,4

In [22]:
df_pay_group['PERCENT_NOT_PAID'] = df_pay_group['NOT_PAID']/df_pay_group['NUM_INSTALMENT_NUMBER']
df_pay_group['OWED'] = df_pay_group['AMT_INSTALMENT']-df_pay_group['AMT_PAYMENT']
df_pay_group['PAYMENTS_MADE']=df_pay_group['NUM_INSTALMENT_NUMBER']-df_pay_group['NOT_PAID']

try:
    df_pay_group['PERCENT_UNDER_PAID'] = df_pay_group['UNDER_PAY_COUNT']/df_pay_group['NUM_INSTALMENT_NUMBER']
except ZeroDivisionError:
    print ("0")

df_pay_group['PERCENT_OWED'] = df_pay_group['OWED']/df_pay_group['AMT_INSTALMENT']
df_pay_group['no_DPD_Percentage'] = 1-(df_pay_group['DPD_Count']/df_pay_group['NUM_INSTALMENT_NUMBER'])

In [33]:
#print(df_pay_group['DPD_Count'].value_counts()[:10])
df_pay_group.sort_values(by='PERCENT_OWED')

,NUM_INSTALMENT_NUMBER,NOT_PAID,DPD,DPD_min,DPD_avg,DPD_Count,AMT_INSTALMENT,AMT_PAYMENT,UNDER_PAY_COUNT,PERCENT_NOT_PAID,OWED,PAYMENTS_MADE,PERCENT_UNDER_PAID,PERCENT_OWED,no_DPD_Percentage
SK_ID_CURR,,,,,,,,,,,,,,,
247019,60,0,1.0,-15.0,-4.300000,2,0.000,2483614.170,0,0.000000,-2483614.170,60,0,-inf,0.966667
249387,11,0,2225.0,-11.0,198.818182,2,0.000,39062.385,0,0.000000,-39062.385,11,0,-inf,0.818182
439267,13,0,1518.0,-47.0,99.538462,1,0.000,18949.140,0,0.000000,-18949.140,13,0,-inf,0.923077
262837,64,0,-5.0,-85.0,-34.187500,0,526902.570,2890134.900,0,0.000000,-2363232.330,64,0,-4.485141,1.000000
416262,17,0,8.0,-46.0,-7.411765,2,442929.645,1248380.820,2,0.000000,-805451.175,17,0.117647,-1.818463,0.882353
193018,24,0,-3.0,-22.0,-12.166667,0,162000.000,324000.000,0,0.000000,-162000.000,24,0,-1.000000,1.000000
282272,18,0,-8.0,-22.0,-14.444444,0,2025000.000,4050000.000,0,0.000000,-2025000.000,18,0,-1.000000,1.000000
188950,2,0,-10.0,-10.0,-10.000000,0,9000.000,18000.000,0,0.000000,-9000.000,2,0,-1.000000,1.000000
372244,16,0,-9.0,-14.0,-11.750000,0,562500.000,1125000.000,0,0.000000,-562500.000,16,0,-1.000000,1.000000
401861,20,0,3.0,-11.0,-5.600000,2,270000.000,540000.000,0,0.000000,-270000.000,20,0,-1.000000,0.900000
132298,32,0,-7.0,-19.0,-13.500000,0,254250.000,508500.000,0,0.000000,-254250.000,32,0,-1.000000,1.000000
338788,2,0,-7.0,-7.0,-7.000000,0,13500.000,27000.000,0,0.000000,-13500.000,2,0,-1.000000,1.000000
254526,34,0,-3.0,-23.0,-15.882353,0,437625.000,875250.000,0,0.000000,-437625.000,34,0,-1.000000,1.000000
268495,4,0,-9.0,-11.0,-10.000000,0,247500.000,495000.000,0,0.000000,-247500.000,4,0,-1.000000,1.000000
155743,2,0,-21.0,-21.0,-21.000000,0,30150.000,60300.000,0,0.000000,-30150.000,2,0,-1.000000,1.000000
293715,10,0,-14.0,-20.0,-17.600000,0,198000.000,396000.000,0,0.000000,-198000.000,10,0,-1.000000,1.000000
358917,22,0,-7.0,-29.0,-15.545455,0,267300.000,534600.000,0,0.000000,-267300.000,22,0,-1.000000,1.000000
402355,10,0,-10.0,-20.0,-15.000000,0,52200.000,104400.000,0,0.000000,-52200.000,10,0,-1.000000,1.000000
360327,6,0,0.0,-11.0,-6.666667,0,159750.000,319500.000,0,0.000000,-159750.000,6,0,-1.000000,1.000000
123343,10,0,-8.0,-12.0,-9.800000,0,225000.000,450000.000,0,0.000000,-225000.000,10,0,-1.000000,1.000000
362205,8,0,-7.0,-11.0,-9.000000,0,234495.000,468990.000,0,0.000000,-234495.000,8,0,-1.000000,1.000000
178690,16,0,-11.0,-17.0,-14.250000,0,226800.000,453600.000,0,0.000000,-226800.000,16,0,-1.000000,1.000000
300624,14,0,-11.0,-13.0,-11.714286,0,189000.000,378000.000,0,0.000000,-189000.000,14,0,-1.000000,1.000000
232948,10,0,0.0,-6.0,-2.400000,0,630742.500,1261485.000,0,0.000000,-630742.500,10,0,-1.000000,1.000000
137196,4,0,-7.0,-20.0,-13.500000,0,90000.000,180000.000,0,0.000000,-90000.000,4,0,-1.000000,1.000000
113542,6,0,-18.0,-26.0,-21.000000,0,180000.000,360000.000,0,0.000000,-180000.000,6,0,-1.000000,1.000000
168487,10,0,-1.0,-36.0,-9.900000,0,750718.620,1497718.620,0,0.000000,-747000.000,10,0,-0.995047,1.000000
322908,9,0,-1.0,-30.0,-19.777778,0,837585.450,1670085.450,0,0.000000,-832500.000,9,0,-0.993928,1.000000
204280,5,0,55.0,-8.0,11.800000,2,125338.185,249873.210,0,0.000000,-124535.025,5,0,-0.993592,0.600000
268570,9,0,69.0,-21.0,8.333333,4,48228.525,96133.680,0,0.000000,-47905.155,9,0,-0.993295,0.555556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245202,7,1,125.0,-43.0,-1.428571,1,112808.925,46381.725,0,0.142857,66427.200,6,0,0.588847,0.857143
309538,10,0,52.0,1.0,18.800000,10,46866.510,19252.755,8,0.000000,27613.755,10,0.8,0.589200,0.000000
324177,18,0,124.0,-16.0,14.222222,13,709906.680,285170.535,16,0.000000,424736.145,18,0.888889,0.598299,0.277778
292201,64,0,102.0,-59.0,1.015625,30,2248316.010,845681.310,36,0.000000,1402634.700,64,0.5625,0.623860,0.531250
376798,9,1,200.0,-52.0,-1.222222,1,112848.345,41435.730,0,0.111111,71412.615,8,0,0.632819,0.888889
415656,113,8,181.0,-31.0,6.106195,28,738305.505,264695.085,26,0.070796,473610.420,105,0.230088,0.641483,0.752212
418486,204,35,1043.0,-30.0,87.044118,42,2663257.815,945596.340,8,0.171569,1717661.475,169,0.0392157,0.644948,0.794118
292953,7,1,149.0,-18.0,10.857143,1,299037.150,104812.650,0,0.142857,194224.500,6,0,0.649500,0.857143
350280,54,1,84.0,-29.0,-4.166667,11,392860.395,134236.350,6,0.018519,258624.045,53,0.111111,0.658310,0.796296
323456,13,3,81.0,-12.0,4.615385,3,220336.110,74822.445,0,0.230769,145513.665,10,0,0.660417,0.769231
332973,3,0,34.0,-12.0,17.333333,2,657656.550,219218.850,3,0.000000,438437.700,3,1,0.666667,0.333333
394217,41,1,332.0,-49.0,5.512195,3,593852.535,185135.535,2,0.024390,408717.000,40,0.0487805,0.688247,0.926829
365842,10,4,97.0,-16.0,27.100000,4,143723.610,43028.190,0,0.400000,100695.420,6,0,0.700618,0.600000
142396,12,1,199.0,-50.0,-11.166667,1,353351.745,103336.605,0,0.083333,250015.140,11,0,0.707553,0.916667
263836,4,1,155.0,-40.0,16.750000,1,206358.795,59912.055,0,0.250000,146446.740,3,0,0.709670,0.750000
369120,4,1,4.0,-81.0,-37.250000,1,26952.975,7793.820,0,0.250000,19159.155,3,0,0.710836,0.750000
150208,99,1,145.0,-29.0,0.373737,3,101772.000,28740.060,0,0.010101,73031.940,98,0,0.717603,0.969697
104101,28,1,388.0,-120.0,-21.321429,1,460139.625,114015.375,0,0.035714,346124.250,27,0,0.752216,0.964286
300548,25,5,201.0,-19.0,24.760000,5,620879.895,133569.090,0,0.200000,487310.805,20,0,0.784871,0.800000
298113,9,1,339.0,-31.0,29.777778,5,216705.195,41739.075,6,0.111111,174966.120,8,0.666667,0.807392,0.444444
388647,9,5,93.0,-16.0,28.333333,5,300216.960,40090.320,0,0.555556,260126.640,4,0,0.866462,0.444444
153598,1,1,667.0,667.0,667.000000,1,233338.680,0.000,0,1.000000,233338.680,0,0,1.000000,0.000000
338747,3,3,88.0,28.0,58.000000,3,61616.295,0.000,0,1.000000,61616.295,0,0,1.000000,0.000000
230272,1,1,210.0,210.0,210.000000,1,79425.045,0.000,0,1.000000,79425.045,0,0,1.000000,0.000000
263534,1,1,121.0,121.0,121.000000,1,99838.530,0.000,0,1.000000,99838.530,0,0,1.000000,0.000000
389262,16,16,476.0,26.0,251.000000,16,105052.320,0.000,0,1.000000,105052.320,0,0,1.000000,0.000000
220039,1,1,152.0,152.0,152.000000,1,54180.090,0.000,0,1.000000,54180.090,0,0,1.000000,0.000000
329430,1,1,2043.0,2043.0,2043.000000,1,104.040,0.000,0,1.000000,104.040,0,0,1.000000,0.000000
151950,1,1,180.0,180.0,180.000000,1,312588.000,0.000,0,1.000000,312588.000,0,0,1.000000,0.000000
405063,34,34,2909.0,1905.0,2407.352941,34,70.560,0.000,0,1.000000,70.560,0,0,1.000000,0.000000

In [24]:
df_pay_group.sort_values(by='PERCENT_NOT_PAID', ascending = False)[:10]

,NUM_INSTALMENT_NUMBER,NOT_PAID,DPD,DPD_min,DPD_avg,DPD_Count,AMT_INSTALMENT,AMT_PAYMENT,UNDER_PAY_COUNT,PERCENT_NOT_PAID,OWED,PAYMENTS_MADE,PERCENT_UNDER_PAID,PERCENT_OWED,no_DPD_Percentage
SK_ID_CURR,,,,,,,,,,,,,,,
405063,34,34,2909.0,1905.0,2407.352941,34,70.560,0.00,0,1.000000,70.560,0,0,1.000000,0.000000
338747,3,3,88.0,28.0,58.000000,3,61616.295,0.00,0,1.000000,61616.295,0,0,1.000000,0.000000
329430,1,1,2043.0,2043.0,2043.000000,1,104.040,0.00,0,1.000000,104.040,0,0,1.000000,0.000000
153598,1,1,667.0,667.0,667.000000,1,233338.680,0.00,0,1.000000,233338.680,0,0,1.000000,0.000000
389262,16,16,476.0,26.0,251.000000,16,105052.320,0.00,0,1.000000,105052.320,0,0,1.000000,0.000000
263534,1,1,121.0,121.0,121.000000,1,99838.530,0.00,0,1.000000,99838.530,0,0,1.000000,0.000000
151950,1,1,180.0,180.0,180.000000,1,312588.000,0.00,0,1.000000,312588.000,0,0,1.000000,0.000000
220039,1,1,152.0,152.0,152.000000,1,54180.090,0.00,0,1.000000,54180.090,0,0,1.000000,0.000000
230272,1,1,210.0,210.0,210.000000,1,79425.045,0.00,0,1.000000,79425.045,0,0,1.000000,0.000000
388647,9,5,93.0,-16.0,28.333333,5,300216.960,40090.32,0,0.555556,260126.640,4,0,0.866462,0.444444

In [25]:
df_pay_group.sort_values(by='no_DPD_Percentage')

,NUM_INSTALMENT_NUMBER,NOT_PAID,DPD,DPD_min,DPD_avg,DPD_Count,AMT_INSTALMENT,AMT_PAYMENT,UNDER_PAY_COUNT,PERCENT_NOT_PAID,OWED,PAYMENTS_MADE,PERCENT_UNDER_PAID,PERCENT_OWED,no_DPD_Percentage
SK_ID_CURR,,,,,,,,,,,,,,,
209679,6,0,8.0,1.0,4.333333,6,25457.535,25457.535,0,0.0,0.000,6,0,0.000000,0.0
433263,1,0,42.0,42.0,42.000000,1,8164.215,8164.215,0,0.0,0.000,1,0,0.000000,0.0
311878,2,0,6.0,5.0,5.500000,2,8743.815,8743.815,0,0.0,0.000,2,0,0.000000,0.0
328263,6,0,20.0,2.0,11.666667,6,14338.800,14338.800,0,0.0,0.000,6,0,0.000000,0.0
384760,11,0,37.0,3.0,17.545455,11,136970.010,74697.885,10,0.0,62272.125,11,0.909091,0.454641,0.0
151097,1,0,4.0,4.0,4.000000,1,6695.235,6695.235,0,0.0,0.000,1,0,0.000000,0.0
313225,3,0,15.0,5.0,11.333333,3,17476.920,17449.830,1,0.0,27.090,3,0.333333,0.001550,0.0
384110,3,0,21.0,6.0,14.000000,3,27971.145,27971.145,0,0.0,0.000,3,0,0.000000,0.0
339681,6,0,14.0,8.0,10.833333,6,58049.190,58049.190,0,0.0,0.000,6,0,0.000000,0.0
253792,1,0,4.0,4.0,4.000000,1,2668.500,2668.500,0,0.0,0.000,1,0,0.000000,0.0
190095,10,0,15.0,7.0,10.600000,10,25372.935,25372.935,0,0.0,0.000,10,0,0.000000,0.0
332132,12,0,39.0,1.0,11.833333,12,57488.580,43104.735,6,0.0,14383.845,12,0.5,0.250204,0.0
141777,1,0,6.0,6.0,6.000000,1,20216.115,20216.115,0,0.0,0.000,1,0,0.000000,0.0
422280,23,0,60.0,18.0,32.956522,23,99435.015,69177.555,14,0.0,30257.460,23,0.608696,0.304294,0.0
348944,1,0,5.0,5.0,5.000000,1,367823.745,367823.745,0,0.0,0.000,1,0,0.000000,0.0
153598,1,1,667.0,667.0,667.000000,1,233338.680,0.000,0,1.0,233338.680,0,0,1.000000,0.0
411077,14,0,49.0,1.0,12.071429,14,74107.755,40924.755,11,0.0,33183.000,14,0.785714,0.447767,0.0
206456,2,0,15.0,4.0,9.500000,2,11884.680,11884.680,0,0.0,0.000,2,0,0.000000,0.0
107241,5,0,484.0,6.0,209.200000,5,0.945,0.945,0,0.0,0.000,5,0,0.000000,0.0
264211,1,0,2.0,2.0,2.000000,1,3172.590,3172.590,0,0.0,0.000,1,0,0.000000,0.0
383433,1,0,1.0,1.0,1.000000,1,8102.160,8102.160,0,0.0,0.000,1,0,0.000000,0.0
233364,7,0,36.0,1.0,17.285714,7,89739.900,51278.400,6,0.0,38461.500,7,0.857143,0.428589,0.0
429485,10,0,25.0,2.0,8.600000,10,73282.950,73282.950,0,0.0,0.000,10,0,0.000000,0.0
162492,8,0,94.0,4.0,38.250000,8,67653.810,33826.905,8,0.0,33826.905,8,1,0.500000,0.0
191436,12,0,28.0,7.0,15.416667,12,60683.895,60683.895,0,0.0,0.000,12,0,0.000000,0.0
122631,1,0,3.0,3.0,3.000000,1,8901.135,8901.135,0,0.0,0.000,1,0,0.000000,0.0
164548,8,0,9.0,3.0,6.000000,8,36585.360,36585.360,0,0.0,0.000,8,0,0.000000,0.0
340009,1,0,13.0,13.0,13.000000,1,6972.390,6972.390,0,0.0,0.000,1,0,0.000000,0.0
413542,12,0,16.0,2.0,7.333333,12,23842.215,23842.215,0,0.0,0.000,12,0,0.000000,0.0
263534,1,1,121.0,121.0,121.000000,1,99838.530,0.000,0,1.0,99838.530,0,0,1.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139121,12,0,-7.0,-24.0,-15.666667,0,232976.340,232976.340,0,0.0,0.000,12,0,0.000000,1.0
215497,11,0,-8.0,-42.0,-34.636364,0,169349.400,169349.400,0,0.0,0.000,11,0,0.000000,1.0
215495,11,0,-1.0,-10.0,-4.181818,0,303421.320,303421.320,0,0.0,0.000,11,0,0.000000,1.0
215491,118,0,0.0,-45.0,-4.533898,0,304940.385,304940.385,0,0.0,0.000,118,0,0.000000,1.0
327691,5,0,-11.0,-47.0,-21.000000,0,26199.675,26199.675,0,0.0,0.000,5,0,0.000000,1.0
215488,41,0,-1.0,-35.0,-11.243902,0,766039.770,833539.770,0,0.0,-67500.000,41,0,-0.088116,1.0
327674,6,0,0.0,-17.0,-12.666667,0,73369.215,73369.215,0,0.0,0.000,6,0,0.000000,1.0
215511,10,0,-13.0,-30.0,-22.700000,0,164695.500,164695.500,0,0.0,0.000,10,0,0.000000,1.0
327671,3,0,0.0,-51.0,-24.000000,0,58414.815,58414.815,0,0.0,0.000,3,0,0.000000,1.0
215512,7,0,-8.0,-23.0,-14.857143,0,225961.785,225961.785,0,0.0,0.000,7,0,0.000000,1.0
327649,6,0,-1.0,-11.0,-3.833333,0,127538.820,127538.820,0,0.0,0.000,6,0,0.000000,1.0
215522,10,0,-8.0,-28.0,-15.100000,0,82164.780,82164.780,0,0.0,0.000,10,0,0.000000,1.0
327651,21,0,0.0,-58.0,-25.095238,0,155580.165,220830.165,0,0.0,-65250.000,21,0,-0.419398,1.0
215521,18,0,-3.0,-11.0,-6.722222,0,583150.725,934150.725,0,0.0,-351000.000,18,0,-0.601903,1.0
215520,18,0,-1.0,-19.0,-8.500000,0,257264.415,257264.415,0,0.0,0.000,18,0,0.000000,1.0
215519,11,0,-12.0,-25.0,-16.818182,0,215512.605,215512.605,0,0.0,0.000,11,0,0.000000,1.0
327656,6,0,-8.0,-12.0,-10.500000,0,104988.150,104988.150,0,0.0,0.000,6,0,0.000000,1.0
327657,32,0,0.0,-32.0,-14.875000,0,505669.140,505669.140,0,0.0,0.000,32,0,0.000000,1.0
215524,6,0,-9.0,-16.0,-13.666667,0,181697.985,181697.985,0,0.0,0.000,6,0,0.000000,1.0
215518,4,0,-14.0,-30.0,-20.500000,0,68414.715,68414.715,0,0.0,0.000,4,0,0.000000,1.0
327660,10,0,-1.0,-26.0,-10.800000,0,50292.540,50292.540,0,0.0,0.000,10,0,0.000000,1.0
327661,20,0,-4.0,-30.0,-16.300000,0,93522.915,93522.915,0,0.0,0.000,20,0,0.000000,1.0
215515,4,0,-11.0,-22.0,-16.750000,0,38177.415,38177.415,0,0.0,0.000,4,0,0.000000,1.0
327663,6,0,-4.0,-62.0,-24.000000,0,252234.000,252234.000,0,0.0,0.000,6,0,0.000000,1.0
327664,10,0,-14.0,-27.0,-20.100000,0,234848.925,234848.925,0,0.0,0.000,10,0,0.000000,1.0
327665,118,0,0.0,-67.0,-8.737288,0,1462606.515,1462606.515,0,0.0,0.000,118,0,0.000000,1.0
139116,21,0,-4.0,-24.0,-12.380952,0,542661.705,542661.705,0,0.0,0.000,21,0,0.000000,1.0
215513,9,0,-1.0,-26.0,-7.555556,0,35595.450,35595.450,0,0.0,0.000,9,0,0.000000,1.0
215517,8,0,-18.0,-24.0,-21.375000,0,62141.760,62141.760,0,0.0,0.000,8,0,0.000000,1.0
149814,11,0,0.0,-38.0,-9.727273,0,127160.010,194654.700,0,0.0,-67494.690,11,0,-0.530786,1.0

In [26]:
print(len(df_pay_group))
print(len(df_POS_group))

339587
337224

In [27]:
sum(train_main['SK_ID_CURR'].isin(df_pay_group.index))/len(train_main)

0.9483985938714388

In [28]:
sum(train_main['SK_ID_CURR'].isin(df_POS_group.index))/len(train_main)

0.9411695841774765

In [29]:
df_pay_group.to_csv('df_pay.csv')
df_POS_group.to_csv('df_POS.csv')