In [2]:
from pandas import DataFrame, Series
import pandas as pd
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [3]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [4]:
# read in the main training csv
train_main = pd.read_csv('home-credit-default-risk/application_train.csv', na_values=['','XNA','XAP'])

In [5]:
print(train_main.shape)
train_main[:5]

(307511, 122)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# Drop records that are too sparse (after previous discovery, these are usually not represented in test data
# Family Status: Unknown
train_main = train_main[train_main['NAME_FAMILY_STATUS'] != 'Unknown'] #2 records with unknown family status
train_main = train_main[train_main['NAME_INCOME_TYPE'] != 'Businessman'] #10 businessman

In [7]:
train_main.shape # 12 records dropped

(307499, 122)

In [8]:
# read in the ancillary csv's
credit_card = pd.read_csv('cleaned_tables/credit_card_summary.csv')
POS = pd.read_csv('cleaned_tables/df_POS_final2.csv')
install = pd.read_csv('cleaned_tables/df_pay_final2.csv')
bureau = pd.read_csv('cleaned_tables/Bureau_features.csv')
prev = pd.read_csv('cleaned_tables/prevapp_finally_train.csv')

### Get column names of additional tables

In [9]:
cred_col = credit_card.columns
credit_col = cred_col[1:]
len(credit_col) #8 extra

8

In [10]:
POS.drop(['DPD_df_POS','count_df_POS'], axis = 1, inplace = True)

In [11]:
POS_col = POS.columns[1:]
len(POS_col) #4 extra

4

In [12]:
install_col = install.columns[1:]
len(install_col) #12 extra

12

In [13]:
bureau_col = bureau.columns[1:]
len(bureau_col) #15 extra

15

In [14]:
prev_col = prev.columns[1:]
len(prev_col) # 10 extra

10

### merge tables

In [15]:
prev[:5]

,ID_CURR,AMT_APPLICATION,NUM_APPLICATIONS,AMT_APPROVED,PCT_APPROVED,MIN_DAYS_DECISION,PCT_APPL_ON_SAME_DAY,min_term,max_term,mean_term,DAYS_TERMINATION
0,100002,179055.00,1,179055.0,1.000000,-606,0.0,24.0,24.0,24.0,-17.0
1,100003,1306309.50,3,1452573.0,1.000000,-746,0.0,6.0,12.0,9.0,-527.0
2,100004,24282.00,1,20106.0,1.000000,-815,0.0,4.0,4.0,4.0,-714.0
3,100006,2449829.34,9,1718644.5,0.555556,-181,0.0,0.0,48.0,18.0,0.0
4,100007,903181.50,6,999832.5,1.000000,-374,0.0,18.0,48.0,30.0,0.0

In [16]:
df = train_main.merge(credit_card, how = 'left', on = 'SK_ID_CURR')
df = df.merge(POS, how = 'left', left_on ='SK_ID_CURR', right_on = 'SK_ID_CURR_df_POS').drop('SK_ID_CURR_df_POS', axis = 1)
df = df.merge(install, how = 'left', left_on = 'SK_ID_CURR', right_on = 'SK_ID_CURR_pay').drop('SK_ID_CURR_pay', axis = 1)
df = df.merge(bureau, how = 'left', on = 'SK_ID_CURR')
df = df.merge(prev, how = 'left', left_on = 'SK_ID_CURR', right_on = 'ID_CURR').drop('ID_CURR',axis = 1)

In [17]:
df[:5]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,AVG_CC_BALANCE,MAX_CC_BALANCE,MIN_CC_BALANCE,MED_CC_BALANCE,MAX_CC_DPD,MIN_CC_DPD,AVG_CC_DPD,ZERO_CC_DPD,max_df_POS,min_df_POS,mean_df_POS,percentage_no_DPD_df_POS,NUM_INSTALMENT_NUMBER_pay,DPD_max_pay,DPD_min_pay,DPD_avg_pay,DPD_Count_pay,AMT_INSTALMENT_pay,AMT_PAYMENT_pay,PERCENT_NOT_PAID_pay,OWED_pay,PERCENT_UNDER_PAID_pay,PERCENT_OWED_pay,no_DPD_Percentage_pay,Percent_BU_CREDIT_ACTIVE,COUNT_BU_CREDIT_ACTIVE,AVG_BU_DAYS_CREDIT,MAX_BU_CREDIT_DAY_OVERDUE,MIN_BU_CREDIT_DAY_OVERDUE,AVG_BU_CREDIT_DAY_OVERDUE,percent_BU_CREDIT_DAY_OVERDUE,MAX_BU_DAYS_CREDIT_ENDDATE,MAX_BU_DAYS_ENDDATE,AVG_BU_CNT_CREDIT_PROLONG,MAX_BU_CNT_CREDIT_PROLONG,SUM_BU_AMT_CREDIT_SUM,COUNT_BU_CREDIT_TYPE,MAX_BU_PERCENT_SUM_OVERDUE,AVG_BU_PERCENT_SUM_OVERDUE,AMT_APPLICATION,NUM_APPLICATIONS,AMT_APPROVED,PCT_APPROVED,MIN_DAYS_DECISION,PCT_APPL_ON_SAME_DAY,min_term,max_term,mean_term,DAYS_TERMINATION
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,19.0,-12.0,-31.0,-20.421053,0.0,219625.695,219625.695,0.0,0.000,0.000000,0.000000,1.000000,0.00,4.0,-645.0,0.0,0.0,0.0,0.0,85.0,-36.0,0.0,0.0,315567.0,2.0,0.0,0.0,179055.00,1.0,179055.0,1.000000,-606.0,0.0,24.0,24.0,24.0,-17.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,25.0,-1.0,-14.0,-7.160000,0.0,1618864.650,1618864.650,0.0,0.000,0.000000,0.000000,1.000000,0.25,4.0,-606.0,0.0,0.0,0.0,0.0,1216.0,0.0,0.0,0.0,1017400.5,2.0,0.0,0.0,1306309.50,3.0,1452573.0,1.000000,-746.0,0.0,6.0,12.0,9.0,-527.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,3.0,-3.0,-11.0,-7.666667,0.0,21288.465,21288.465,0.0,0.000,0.000000,0.000000,1.000000,0.00,2.0,-408.0,0.0,0.0,0.0,0.0,-382.0,-382.0,0.0,0.0,189037.8,1.0,0.0,0.0,24282.00,1.0,20106.0,1.000000,-815.0,0.0,4.0,4.0,4.0,-714.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,16.0,-1.0,-77.0,-19.375000,0.0,1007153.415,1007153.415,0.0,0.000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2449829.34,9.0,1718644.5,0.555556,-181.0,0.0,0.0,48.0,18.0,0.0
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,66.0,12.0,-31.0,-3.636364,16.0,835985.340,806127.975,0.0,29857.365,0.090909,0.035715,0.757576,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,903181.50,6.0,999832.5,1.000000,-374.0,0.0,18.0,48.0,30.0,0.0

### Fill nas for the summarized columns
if they did not appear in other tables, they did not have previous applications, credit cards, etc.

In [18]:
addl_col = cred_col.append([POS_col, install_col, bureau_col, prev_col]) # append other tables' columns as well
df[addl_col] = df[addl_col].fillna(0)
df[:5]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,AVG_CC_BALANCE,MAX_CC_BALANCE,MIN_CC_BALANCE,MED_CC_BALANCE,MAX_CC_DPD,MIN_CC_DPD,AVG_CC_DPD,ZERO_CC_DPD,max_df_POS,min_df_POS,mean_df_POS,percentage_no_DPD_df_POS,NUM_INSTALMENT_NUMBER_pay,DPD_max_pay,DPD_min_pay,DPD_avg_pay,DPD_Count_pay,AMT_INSTALMENT_pay,AMT_PAYMENT_pay,PERCENT_NOT_PAID_pay,OWED_pay,PERCENT_UNDER_PAID_pay,PERCENT_OWED_pay,no_DPD_Percentage_pay,Percent_BU_CREDIT_ACTIVE,COUNT_BU_CREDIT_ACTIVE,AVG_BU_DAYS_CREDIT,MAX_BU_CREDIT_DAY_OVERDUE,MIN_BU_CREDIT_DAY_OVERDUE,AVG_BU_CREDIT_DAY_OVERDUE,percent_BU_CREDIT_DAY_OVERDUE,MAX_BU_DAYS_CREDIT_ENDDATE,MAX_BU_DAYS_ENDDATE,AVG_BU_CNT_CREDIT_PROLONG,MAX_BU_CNT_CREDIT_PROLONG,SUM_BU_AMT_CREDIT_SUM,COUNT_BU_CREDIT_TYPE,MAX_BU_PERCENT_SUM_OVERDUE,AVG_BU_PERCENT_SUM_OVERDUE,AMT_APPLICATION,NUM_APPLICATIONS,AMT_APPROVED,PCT_APPROVED,MIN_DAYS_DECISION,PCT_APPL_ON_SAME_DAY,min_term,max_term,mean_term,DAYS_TERMINATION
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,19.0,-12.0,-31.0,-20.421053,0.0,219625.695,219625.695,0.0,0.000,0.000000,0.000000,1.000000,0.00,4.0,-645.0,0.0,0.0,0.0,0.0,85.0,-36.0,0.0,0.0,315567.0,2.0,0.0,0.0,179055.00,1.0,179055.0,1.000000,-606.0,0.0,24.0,24.0,24.0,-17.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,25.0,-1.0,-14.0,-7.160000,0.0,1618864.650,1618864.650,0.0,0.000,0.000000,0.000000,1.000000,0.25,4.0,-606.0,0.0,0.0,0.0,0.0,1216.0,0.0,0.0,0.0,1017400.5,2.0,0.0,0.0,1306309.50,3.0,1452573.0,1.000000,-746.0,0.0,6.0,12.0,9.0,-527.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,-3.0,-11.0,-7.666667,0.0,21288.465,21288.465,0.0,0.000,0.000000,0.000000,1.000000,0.00,2.0,-408.0,0.0,0.0,0.0,0.0,-382.0,-382.0,0.0,0.0,189037.8,1.0,0.0,0.0,24282.00,1.0,20106.0,1.000000,-815.0,0.0,4.0,4.0,4.0,-714.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,16.0,-1.0,-77.0,-19.375000,0.0,1007153.415,1007153.415,0.0,0.000,0.000000,0.000000,1.000000,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2449829.34,9.0,1718644.5,0.555556,-181.0,0.0,0.0,48.0,18.0,0.0
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,66.0,12.0,-31.0,-3.636364,16.0,835985.340,806127.975,0.0,29857.365,0.090909,0.035715,0.757576,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,903181.50,6.0,999832.5,1.000000,-374.0,0.0,18.0,48.0,30.0,0.0

### Required preprocessing steps for the whole table
1. Split train / test
2. Fill NAs - following the decision made when exploring the main table
3. Set up categorical variables
4. Rebalance / SMOTE

### 1. Split train/test

In [19]:
X = df[df.columns[2:]]
print(X.shape)
X[:2]

(307499, 169)

,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,AVG_CC_BALANCE,MAX_CC_BALANCE,MIN_CC_BALANCE,MED_CC_BALANCE,MAX_CC_DPD,MIN_CC_DPD,AVG_CC_DPD,ZERO_CC_DPD,max_df_POS,min_df_POS,mean_df_POS,percentage_no_DPD_df_POS,NUM_INSTALMENT_NUMBER_pay,DPD_max_pay,DPD_min_pay,DPD_avg_pay,DPD_Count_pay,AMT_INSTALMENT_pay,AMT_PAYMENT_pay,PERCENT_NOT_PAID_pay,OWED_pay,PERCENT_UNDER_PAID_pay,PERCENT_OWED_pay,no_DPD_Percentage_pay,Percent_BU_CREDIT_ACTIVE,COUNT_BU_CREDIT_ACTIVE,AVG_BU_DAYS_CREDIT,MAX_BU_CREDIT_DAY_OVERDUE,MIN_BU_CREDIT_DAY_OVERDUE,AVG_BU_CREDIT_DAY_OVERDUE,percent_BU_CREDIT_DAY_OVERDUE,MAX_BU_DAYS_CREDIT_ENDDATE,MAX_BU_DAYS_ENDDATE,AVG_BU_CNT_CREDIT_PROLONG,MAX_BU_CNT_CREDIT_PROLONG,SUM_BU_AMT_CREDIT_SUM,COUNT_BU_CREDIT_TYPE,MAX_BU_PERCENT_SUM_OVERDUE,AVG_BU_PERCENT_SUM_OVERDUE,AMT_APPLICATION,NUM_APPLICATIONS,AMT_APPROVED,PCT_APPROVED,MIN_DAYS_DECISION,PCT_APPL_ON_SAME_DAY,min_term,max_term,mean_term,DAYS_TERMINATION
0,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,19.0,-12.0,-31.0,-20.421053,0.0,219625.695,219625.695,0.0,0.0,0.0,0.0,1.0,0.00,4.0,-645.0,0.0,0.0,0.0,0.0,85.0,-36.0,0.0,0.0,315567.0,2.0,0.0,0.0,179055.0,1.0,179055.0,1.0,-606.0,0.0,24.0,24.0,24.0,-17.0
1,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,25.0,-1.0,-14.0,-7.160000,0.0,1618864.650,1618864.650,0.0,0.0,0.0,0.0,1.0,0.25,4.0,-606.0,0.0,0.0,0.0,0.0,1216.0,0.0,0.0,0.0,1017400.5,2.0,0.0,0.0,1306309.5,3.0,1452573.0,1.0,-746.0,0.0,6.0,12.0,9.0,-527.0

In [20]:
y = df['TARGET']
print(y.shape)

(307499,)

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [22]:
print(len(X_train),len(X_test),len(y_train),len(y_test))
print(len(y_train[y_train == 0])/len(y_train),len(y_test[y_test == 0])/len(y_test))

245999 61500 245999 61500
0.9190728417595193 0.9200487804878049

### 2. Fill in missing values

In [23]:
# Drop highly correlated "current housing" attributes
X_train_nona = X_train.drop(['APARTMENTS_AVG',
'APARTMENTS_MODE',
'BASEMENTAREA_AVG',
'BASEMENTAREA_MODE',
'COMMONAREA_AVG',
'COMMONAREA_MODE',
'ELEVATORS_AVG',
'ELEVATORS_MODE',
'ENTRANCES_AVG',
'ENTRANCES_MODE',
'FLOORSMAX_AVG',
'FLOORSMAX_MODE',
'FLOORSMIN_AVG',
'FLOORSMIN_MODE',
'LANDAREA_AVG',
'LANDAREA_MODE',
'LIVINGAPARTMENTS_AVG',
'LIVINGAPARTMENTS_MODE',
'LIVINGAREA_AVG',
'LIVINGAREA_MODE',
'NONLIVINGAPARTMENTS_AVG',
'NONLIVINGAPARTMENTS_MODE',
'NONLIVINGAREA_AVG',
'NONLIVINGAREA_MODE',
'YEARS_BEGINEXPLUATATION_AVG',
'YEARS_BEGINEXPLUATATION_MEDI',
'YEARS_BEGINEXPLUATATION_MODE',
'YEARS_BUILD_AVG',
'YEARS_BUILD_MODE',
'DEF_60_CNT_SOCIAL_CIRCLE',
'OBS_60_CNT_SOCIAL_CIRCLE'], axis = 1)

X_test_nona = X_test.drop(['APARTMENTS_AVG',
'APARTMENTS_MODE',
'BASEMENTAREA_AVG',
'BASEMENTAREA_MODE',
'COMMONAREA_AVG',
'COMMONAREA_MODE',
'ELEVATORS_AVG',
'ELEVATORS_MODE',
'ENTRANCES_AVG',
'ENTRANCES_MODE',
'FLOORSMAX_AVG',
'FLOORSMAX_MODE',
'FLOORSMIN_AVG',
'FLOORSMIN_MODE',
'LANDAREA_AVG',
'LANDAREA_MODE',
'LIVINGAPARTMENTS_AVG',
'LIVINGAPARTMENTS_MODE',
'LIVINGAREA_AVG',
'LIVINGAREA_MODE',
'NONLIVINGAPARTMENTS_AVG',
'NONLIVINGAPARTMENTS_MODE',
'NONLIVINGAREA_AVG',
'NONLIVINGAREA_MODE',
'YEARS_BEGINEXPLUATATION_AVG',
'YEARS_BEGINEXPLUATATION_MEDI',
'YEARS_BEGINEXPLUATATION_MODE',
'YEARS_BUILD_AVG',
'YEARS_BUILD_MODE',
'DEF_60_CNT_SOCIAL_CIRCLE',
'OBS_60_CNT_SOCIAL_CIRCLE'], axis = 1)

In [24]:
print(X_train_nona.shape, X_test_nona.shape) # 31 columns dropped; 169 --> 138

(245999, 138) (61500, 138)

In [25]:
# Filling with Medians
columns_with_median = ['COMMONAREA_MEDI',
'LIVINGAPARTMENTS_MEDI',
'FLOORSMIN_MEDI',
'LANDAREA_MEDI',
'BASEMENTAREA_MEDI',
'ELEVATORS_MEDI',
'APARTMENTS_MEDI',
'ENTRANCES_MEDI',
'LIVINGAREA_MEDI',
'FLOORSMAX_MEDI',
'AMT_GOODS_PRICE',
'AMT_ANNUITY']

for col in columns_with_median:
    X_train_nona[col].fillna(X_train_nona[col].median(), inplace = True)
    X_test_nona[col].fillna(X_train_nona[col].median(), inplace = True)

In [26]:
# Filling with Means
columns_with_means = ['YEARS_BUILD_MEDI',
'EXT_SOURCE_1',
'TOTALAREA_MODE',
'EXT_SOURCE_3',
'EXT_SOURCE_2']

for col in columns_with_means:
    X_train_nona[col].fillna(X_train_nona[col].mean(), inplace = True)
    X_test_nona[col].fillna(X_train_nona[col].mean(), inplace = True)

In [27]:
# Fill with Mode
columns_with_modes = ['FONDKAPREMONT_MODE', 
'HOUSETYPE_MODE',
'EMERGENCYSTATE_MODE']

for col in columns_with_modes:
    X_train_nona[col].fillna(X_train_nona[col].mode()[0], inplace = True)
    X_test_nona[col].fillna(X_train_nona[col].mode()[0], inplace = True)

In [28]:
# Fill with 0's

columns_with_0s = ['NONLIVINGAPARTMENTS_MEDI',
'OWN_CAR_AGE',
'NONLIVINGAREA_MEDI',
'AMT_REQ_CREDIT_BUREAU_YEAR',
'AMT_REQ_CREDIT_BUREAU_DAY',
'AMT_REQ_CREDIT_BUREAU_QRT',
'AMT_REQ_CREDIT_BUREAU_WEEK',
'AMT_REQ_CREDIT_BUREAU_HOUR',
'AMT_REQ_CREDIT_BUREAU_MON',
'OBS_30_CNT_SOCIAL_CIRCLE',
'DEF_30_CNT_SOCIAL_CIRCLE',
'CNT_FAM_MEMBERS',
'DAYS_LAST_PHONE_CHANGE']

for col in columns_with_0s:
    X_train_nona[col].fillna(0, inplace = True)
    X_test_nona[col].fillna(0, inplace = True)

In [29]:
# Other special cases
X_train_nona['WALLSMATERIAL_MODE'].fillna("Others",inplace = True)
X_train_nona['OCCUPATION_TYPE'].fillna("Unemployed",inplace = True)
X_train_nona['ORGANIZATION_TYPE'].fillna("Retired",inplace = True)
X_train_nona['NAME_TYPE_SUITE'].fillna("Unaccompanied",inplace = True)
X_train_nona['CODE_GENDER'].fillna("F",inplace = True)

X_test_nona['WALLSMATERIAL_MODE'].fillna("Others",inplace = True)
X_test_nona['OCCUPATION_TYPE'].fillna("Unemployed",inplace = True)
X_test_nona['ORGANIZATION_TYPE'].fillna("Retired",inplace = True)
X_test_nona['NAME_TYPE_SUITE'].fillna("Unaccompanied",inplace = True)
X_test_nona['CODE_GENDER'].fillna("F",inplace = True)

In [30]:
# verify that there's no more missing values in the training data
(X_train_nona.isnull().sum() / len(X_train_nona)*100).sort_values(ascending = False)

DAYS_TERMINATION                 0.0
BASEMENTAREA_MEDI                0.0
FLOORSMIN_MEDI                   0.0
FLOORSMAX_MEDI                   0.0
ENTRANCES_MEDI                   0.0
ELEVATORS_MEDI                   0.0
COMMONAREA_MEDI                  0.0
YEARS_BUILD_MEDI                 0.0
APARTMENTS_MEDI                  0.0
LIVE_REGION_NOT_WORK_REGION      0.0
EXT_SOURCE_3                     0.0
EXT_SOURCE_2                     0.0
EXT_SOURCE_1                     0.0
ORGANIZATION_TYPE                0.0
LIVE_CITY_NOT_WORK_CITY          0.0
REG_CITY_NOT_WORK_CITY           0.0
LANDAREA_MEDI                    0.0
LIVINGAPARTMENTS_MEDI            0.0
LIVINGAREA_MEDI                  0.0
NONLIVINGAPARTMENTS_MEDI         0.0
NONLIVINGAREA_MEDI               0.0
FONDKAPREMONT_MODE               0.0
HOUSETYPE_MODE                   0.0
TOTALAREA_MODE                   0.0
WALLSMATERIAL_MODE               0.0
EMERGENCYSTATE_MODE              0.0
OBS_30_CNT_SOCIAL_CIRCLE         0.0
DEF_30_CNT_SOCIAL_CIRCLE         0.0
DAYS_LAST_PHONE_CHANGE           0.0
FLAG_DOCUMENT_2                  0.0
FLAG_DOCUMENT_3                  0.0
FLAG_DOCUMENT_4                  0.0
FLAG_DOCUMENT_5                  0.0
REG_CITY_NOT_LIVE_CITY           0.0
REG_REGION_NOT_WORK_REGION       0.0
mean_term                        0.0
AMT_GOODS_PRICE                  0.0
REGION_POPULATION_RELATIVE       0.0
NAME_HOUSING_TYPE                0.0
NAME_FAMILY_STATUS               0.0
NAME_EDUCATION_TYPE              0.0
NAME_INCOME_TYPE                 0.0
NAME_TYPE_SUITE                  0.0
AMT_ANNUITY                      0.0
REG_REGION_NOT_LIVE_REGION       0.0
AMT_CREDIT                       0.0
AMT_INCOME_TOTAL                 0.0
CNT_CHILDREN                     0.0
FLAG_OWN_REALTY                  0.0
FLAG_OWN_CAR                     0.0
CODE_GENDER                      0.0
DAYS_BIRTH                       0.0
DAYS_EMPLOYED                    0.0
DAYS_REGISTRATION                0.0
DAYS_ID_PUBLISH                  0.0
OWN_CAR_AGE                      0.0
FLAG_MOBIL                       0.0
FLAG_EMP_PHONE                   0.0
FLAG_WORK_PHONE                  0.0
FLAG_CONT_MOBILE                 0.0
FLAG_PHONE                       0.0
FLAG_EMAIL                       0.0
OCCUPATION_TYPE                  0.0
CNT_FAM_MEMBERS                  0.0
REGION_RATING_CLIENT             0.0
REGION_RATING_CLIENT_W_CITY      0.0
WEEKDAY_APPR_PROCESS_START       0.0
HOUR_APPR_PROCESS_START          0.0
FLAG_DOCUMENT_6                  0.0
FLAG_DOCUMENT_7                  0.0
FLAG_DOCUMENT_8                  0.0
no_DPD_Percentage_pay            0.0
AVG_BU_CREDIT_DAY_OVERDUE        0.0
MIN_BU_CREDIT_DAY_OVERDUE        0.0
MAX_BU_CREDIT_DAY_OVERDUE        0.0
AVG_BU_DAYS_CREDIT               0.0
COUNT_BU_CREDIT_ACTIVE           0.0
Percent_BU_CREDIT_ACTIVE         0.0
PERCENT_OWED_pay                 0.0
FLAG_DOCUMENT_9                  0.0
PERCENT_UNDER_PAID_pay           0.0
OWED_pay                         0.0
PERCENT_NOT_PAID_pay             0.0
AMT_PAYMENT_pay                  0.0
AMT_INSTALMENT_pay               0.0
DPD_Count_pay                    0.0
percent_BU_CREDIT_DAY_OVERDUE    0.0
MAX_BU_DAYS_CREDIT_ENDDATE       0.0
MAX_BU_DAYS_ENDDATE              0.0
AVG_BU_CNT_CREDIT_PROLONG        0.0
MAX_BU_CNT_CREDIT_PROLONG        0.0
SUM_BU_AMT_CREDIT_SUM            0.0
COUNT_BU_CREDIT_TYPE             0.0
MAX_BU_PERCENT_SUM_OVERDUE       0.0
AVG_BU_PERCENT_SUM_OVERDUE       0.0
AMT_APPLICATION                  0.0
NUM_APPLICATIONS                 0.0
AMT_APPROVED                     0.0
PCT_APPROVED                     0.0
MIN_DAYS_DECISION                0.0
PCT_APPL_ON_SAME_DAY             0.0
min_term                         0.0
max_term                         0.0
DPD_avg_pay                      0.0
DPD_min_pay                      0.0
DPD_max_pay                      0.0
AMT_REQ_CREDIT_BUREAU_WEEK       0.0
FLAG_DOCUMENT_10                 0.0
FLAG_DOCUMENT_11                 0.0
FLAG_DOCUMENT_12                 0.0
FLAG_DOCUMENT_13                 0.0
FLAG_DOCUMENT_14                 0.0
FLAG_DOCUMENT_15                 0.0
FLAG_DOCUMENT_16                 0.0
FLAG_DOCUMENT_17                 0.0
FLAG_DOCUMENT_18                 0.0
FLAG_DOCUMENT_19                 0.0
FLAG_DOCUMENT_20                 0.0
FLAG_DOCUMENT_21                 0.0
AMT_REQ_CREDIT_BUREAU_HOUR       0.0
AMT_REQ_CREDIT_BUREAU_DAY        0.0
AMT_REQ_CREDIT_BUREAU_MON        0.0
NUM_INSTALMENT_NUMBER_pay        0.0
AMT_REQ_CREDIT_BUREAU_QRT        0.0
AMT_REQ_CREDIT_BUREAU_YEAR       0.0
AVG_CC_BALANCE                   0.0
MAX_CC_BALANCE                   0.0
MIN_CC_BALANCE                   0.0
MED_CC_BALANCE                   0.0
MAX_CC_DPD                       0.0
MIN_CC_DPD                       0.0
AVG_CC_DPD                       0.0
ZERO_CC_DPD                      0.0
max_df_POS                       0.0
min_df_POS                       0.0
mean_df_POS                      0.0
percentage_no_DPD_df_POS         0.0
NAME_CONTRACT_TYPE               0.0
dtype: float64

In [31]:
(X_test_nona.isnull().sum() / len(X_test_nona)*100).sort_values(ascending = False)

DAYS_TERMINATION                 0.0
BASEMENTAREA_MEDI                0.0
FLOORSMIN_MEDI                   0.0
FLOORSMAX_MEDI                   0.0
ENTRANCES_MEDI                   0.0
ELEVATORS_MEDI                   0.0
COMMONAREA_MEDI                  0.0
YEARS_BUILD_MEDI                 0.0
APARTMENTS_MEDI                  0.0
LIVE_REGION_NOT_WORK_REGION      0.0
EXT_SOURCE_3                     0.0
EXT_SOURCE_2                     0.0
EXT_SOURCE_1                     0.0
ORGANIZATION_TYPE                0.0
LIVE_CITY_NOT_WORK_CITY          0.0
REG_CITY_NOT_WORK_CITY           0.0
LANDAREA_MEDI                    0.0
LIVINGAPARTMENTS_MEDI            0.0
LIVINGAREA_MEDI                  0.0
NONLIVINGAPARTMENTS_MEDI         0.0
NONLIVINGAREA_MEDI               0.0
FONDKAPREMONT_MODE               0.0
HOUSETYPE_MODE                   0.0
TOTALAREA_MODE                   0.0
WALLSMATERIAL_MODE               0.0
EMERGENCYSTATE_MODE              0.0
OBS_30_CNT_SOCIAL_CIRCLE         0.0
DEF_30_CNT_SOCIAL_CIRCLE         0.0
DAYS_LAST_PHONE_CHANGE           0.0
FLAG_DOCUMENT_2                  0.0
FLAG_DOCUMENT_3                  0.0
FLAG_DOCUMENT_4                  0.0
FLAG_DOCUMENT_5                  0.0
REG_CITY_NOT_LIVE_CITY           0.0
REG_REGION_NOT_WORK_REGION       0.0
mean_term                        0.0
AMT_GOODS_PRICE                  0.0
REGION_POPULATION_RELATIVE       0.0
NAME_HOUSING_TYPE                0.0
NAME_FAMILY_STATUS               0.0
NAME_EDUCATION_TYPE              0.0
NAME_INCOME_TYPE                 0.0
NAME_TYPE_SUITE                  0.0
AMT_ANNUITY                      0.0
REG_REGION_NOT_LIVE_REGION       0.0
AMT_CREDIT                       0.0
AMT_INCOME_TOTAL                 0.0
CNT_CHILDREN                     0.0
FLAG_OWN_REALTY                  0.0
FLAG_OWN_CAR                     0.0
CODE_GENDER                      0.0
DAYS_BIRTH                       0.0
DAYS_EMPLOYED                    0.0
DAYS_REGISTRATION                0.0
DAYS_ID_PUBLISH                  0.0
OWN_CAR_AGE                      0.0
FLAG_MOBIL                       0.0
FLAG_EMP_PHONE                   0.0
FLAG_WORK_PHONE                  0.0
FLAG_CONT_MOBILE                 0.0
FLAG_PHONE                       0.0
FLAG_EMAIL                       0.0
OCCUPATION_TYPE                  0.0
CNT_FAM_MEMBERS                  0.0
REGION_RATING_CLIENT             0.0
REGION_RATING_CLIENT_W_CITY      0.0
WEEKDAY_APPR_PROCESS_START       0.0
HOUR_APPR_PROCESS_START          0.0
FLAG_DOCUMENT_6                  0.0
FLAG_DOCUMENT_7                  0.0
FLAG_DOCUMENT_8                  0.0
no_DPD_Percentage_pay            0.0
AVG_BU_CREDIT_DAY_OVERDUE        0.0
MIN_BU_CREDIT_DAY_OVERDUE        0.0
MAX_BU_CREDIT_DAY_OVERDUE        0.0
AVG_BU_DAYS_CREDIT               0.0
COUNT_BU_CREDIT_ACTIVE           0.0
Percent_BU_CREDIT_ACTIVE         0.0
PERCENT_OWED_pay                 0.0
FLAG_DOCUMENT_9                  0.0
PERCENT_UNDER_PAID_pay           0.0
OWED_pay                         0.0
PERCENT_NOT_PAID_pay             0.0
AMT_PAYMENT_pay                  0.0
AMT_INSTALMENT_pay               0.0
DPD_Count_pay                    0.0
percent_BU_CREDIT_DAY_OVERDUE    0.0
MAX_BU_DAYS_CREDIT_ENDDATE       0.0
MAX_BU_DAYS_ENDDATE              0.0
AVG_BU_CNT_CREDIT_PROLONG        0.0
MAX_BU_CNT_CREDIT_PROLONG        0.0
SUM_BU_AMT_CREDIT_SUM            0.0
COUNT_BU_CREDIT_TYPE             0.0
MAX_BU_PERCENT_SUM_OVERDUE       0.0
AVG_BU_PERCENT_SUM_OVERDUE       0.0
AMT_APPLICATION                  0.0
NUM_APPLICATIONS                 0.0
AMT_APPROVED                     0.0
PCT_APPROVED                     0.0
MIN_DAYS_DECISION                0.0
PCT_APPL_ON_SAME_DAY             0.0
min_term                         0.0
max_term                         0.0
DPD_avg_pay                      0.0
DPD_min_pay                      0.0
DPD_max_pay                      0.0
AMT_REQ_CREDIT_BUREAU_WEEK       0.0
FLAG_DOCUMENT_10                 0.0
FLAG_DOCUMENT_11                 0.0
FLAG_DOCUMENT_12                 0.0
FLAG_DOCUMENT_13                 0.0
FLAG_DOCUMENT_14                 0.0
FLAG_DOCUMENT_15                 0.0
FLAG_DOCUMENT_16                 0.0
FLAG_DOCUMENT_17                 0.0
FLAG_DOCUMENT_18                 0.0
FLAG_DOCUMENT_19                 0.0
FLAG_DOCUMENT_20                 0.0
FLAG_DOCUMENT_21                 0.0
AMT_REQ_CREDIT_BUREAU_HOUR       0.0
AMT_REQ_CREDIT_BUREAU_DAY        0.0
AMT_REQ_CREDIT_BUREAU_MON        0.0
NUM_INSTALMENT_NUMBER_pay        0.0
AMT_REQ_CREDIT_BUREAU_QRT        0.0
AMT_REQ_CREDIT_BUREAU_YEAR       0.0
AVG_CC_BALANCE                   0.0
MAX_CC_BALANCE                   0.0
MIN_CC_BALANCE                   0.0
MED_CC_BALANCE                   0.0
MAX_CC_DPD                       0.0
MIN_CC_DPD                       0.0
AVG_CC_DPD                       0.0
ZERO_CC_DPD                      0.0
max_df_POS                       0.0
min_df_POS                       0.0
mean_df_POS                      0.0
percentage_no_DPD_df_POS         0.0
NAME_CONTRACT_TYPE               0.0
dtype: float64

# Would need to do the same for testing to check model accuracy

### 3. Identify and codify categorical columns - X_train and X_test

### Identify categorical columns

In [32]:
# Categorical columns with strings
string_categorical = X_train_nona.columns[X_train_nona.dtypes == 'object']
s1 = df[string_categorical].nunique()

In [33]:
# string binary
binary_cat = s1[s1 ==2].index 
binary_cat

Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'EMERGENCYSTATE_MODE'],
      dtype='object')

In [34]:
# Categorical columns have numerical values
s2 = X_train_nona.loc[:,df.dtypes != 'object'].nunique()

In [35]:
# numerical binary
binary_cat = binary_cat.append(s2[s2==2].index[1:]) #numerical binary; exclude target

In [36]:
#all binary
binary_cat

Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'EMERGENCYSTATE_MODE', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE',
       'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL',
       'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION',
       'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY',
       'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'FLAG_DOCUMENT_2',
       'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5',
       'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8',
       'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11',
       'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14',
       'FLAG_DOCUMENT_15', 'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17',
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21'],
      dtype='object')

In [37]:
# all non-binary categorical columns
non_bi_cat = s1[s1>2].index # string
non_bi_cat = non_bi_cat.append(s2[(s2>2) & (s2<5)].index) # numerical
non_bi_cat # all

Index(['NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE',
       'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE',
       'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'REGION_RATING_CLIENT',
       'REGION_RATING_CLIENT_W_CITY'],
      dtype='object')

In [38]:
print(len(binary_cat), len(non_bi_cat), len(X_train_nona.columns))

36 13 138

### Codify categorical columns
- Binary: label encoder
- Non-binary: get_dummies

In [39]:
# binary
for column in binary_cat:
    X_train_nona[column] = X_train_nona[column].astype('category').cat.codes
    X_test_nona[column] = X_test_nona[column].astype('category').cat.codes

In [40]:
# verifying everyone has two categories
X_train_nona[binary_cat].nunique()

NAME_CONTRACT_TYPE             2
CODE_GENDER                    2
FLAG_OWN_CAR                   2
FLAG_OWN_REALTY                2
EMERGENCYSTATE_MODE            2
FLAG_EMP_PHONE                 2
FLAG_WORK_PHONE                2
FLAG_CONT_MOBILE               2
FLAG_PHONE                     2
FLAG_EMAIL                     2
REG_REGION_NOT_LIVE_REGION     2
REG_REGION_NOT_WORK_REGION     2
LIVE_REGION_NOT_WORK_REGION    2
REG_CITY_NOT_LIVE_CITY         2
REG_CITY_NOT_WORK_CITY         2
LIVE_CITY_NOT_WORK_CITY        2
FLAG_DOCUMENT_2                2
FLAG_DOCUMENT_3                2
FLAG_DOCUMENT_4                2
FLAG_DOCUMENT_5                2
FLAG_DOCUMENT_6                2
FLAG_DOCUMENT_7                2
FLAG_DOCUMENT_8                2
FLAG_DOCUMENT_9                2
FLAG_DOCUMENT_10               2
FLAG_DOCUMENT_11               2
FLAG_DOCUMENT_12               2
FLAG_DOCUMENT_13               2
FLAG_DOCUMENT_14               2
FLAG_DOCUMENT_15               2
FLAG_DOCUMENT_16               2
FLAG_DOCUMENT_17               2
FLAG_DOCUMENT_18               2
FLAG_DOCUMENT_19               2
FLAG_DOCUMENT_20               2
FLAG_DOCUMENT_21               2
dtype: int64

In [41]:
# non-binary
X_train_nona = pd.get_dummies(X_train_nona,
                            prefix=non_bi_cat,
                            columns=non_bi_cat)
X_train_nona.shape #up from 138

(245999, 259)

In [42]:
X_test_nona = pd.get_dummies(X_test_nona,
                            prefix=non_bi_cat,
                            columns=non_bi_cat)
X_test_nona.shape #same with training

(61500, 259)

In [43]:
# X_train_nona.columns.intersection(X_test_nona.columns)
X_train_nona.columns.symmetric_difference(X_test_nona.columns) #identical sets of training predictors

Index([], dtype='object')

In [ ]:
# For SMOTING purpose:
#Turning all categorical columns into object type
for column in X_train_nona.columns:
    if(len(X_train_nona[column].value_counts())<=2):
        X_train_nona[column] = X_train_nona[column].astype('object')

#return column index of categorical columns
cat_col_index = []
for column in X_train_nona.columns:
    if(X_train_nona[column].dtype == 'object'):
        cat_col_index.append(X_train_nona.columns.get_loc(column))

### 4. Rebalance the training data with SMOTE

In [44]:
# check to ensure no column has infinity
np.isinf(X_train_nona).nunique() # all values returned 1

NAME_CONTRACT_TYPE                                   1
CODE_GENDER                                          1
FLAG_OWN_CAR                                         1
FLAG_OWN_REALTY                                      1
CNT_CHILDREN                                         1
AMT_INCOME_TOTAL                                     1
AMT_CREDIT                                           1
AMT_ANNUITY                                          1
AMT_GOODS_PRICE                                      1
REGION_POPULATION_RELATIVE                           1
DAYS_BIRTH                                           1
DAYS_EMPLOYED                                        1
DAYS_REGISTRATION                                    1
DAYS_ID_PUBLISH                                      1
OWN_CAR_AGE                                          1
FLAG_MOBIL                                           1
FLAG_EMP_PHONE                                       1
FLAG_WORK_PHONE                                      1
FLAG_CONT_MOBILE                                     1
FLAG_PHONE                                           1
FLAG_EMAIL                                           1
CNT_FAM_MEMBERS                                      1
HOUR_APPR_PROCESS_START                              1
REG_REGION_NOT_LIVE_REGION                           1
REG_REGION_NOT_WORK_REGION                           1
LIVE_REGION_NOT_WORK_REGION                          1
REG_CITY_NOT_LIVE_CITY                               1
REG_CITY_NOT_WORK_CITY                               1
LIVE_CITY_NOT_WORK_CITY                              1
EXT_SOURCE_1                                         1
EXT_SOURCE_2                                         1
EXT_SOURCE_3                                         1
APARTMENTS_MEDI                                      1
BASEMENTAREA_MEDI                                    1
YEARS_BUILD_MEDI                                     1
COMMONAREA_MEDI                                      1
ELEVATORS_MEDI                                       1
ENTRANCES_MEDI                                       1
FLOORSMAX_MEDI                                       1
FLOORSMIN_MEDI                                       1
LANDAREA_MEDI                                        1
LIVINGAPARTMENTS_MEDI                                1
LIVINGAREA_MEDI                                      1
NONLIVINGAPARTMENTS_MEDI                             1
NONLIVINGAREA_MEDI                                   1
TOTALAREA_MODE                                       1
EMERGENCYSTATE_MODE                                  1
OBS_30_CNT_SOCIAL_CIRCLE                             1
DEF_30_CNT_SOCIAL_CIRCLE                             1
DAYS_LAST_PHONE_CHANGE                               1
FLAG_DOCUMENT_2                                      1
FLAG_DOCUMENT_3                                      1
FLAG_DOCUMENT_4                                      1
FLAG_DOCUMENT_5                                      1
FLAG_DOCUMENT_6                                      1
FLAG_DOCUMENT_7                                      1
FLAG_DOCUMENT_8                                      1
FLAG_DOCUMENT_9                                      1
FLAG_DOCUMENT_10                                     1
FLAG_DOCUMENT_11                                     1
FLAG_DOCUMENT_12                                     1
FLAG_DOCUMENT_13                                     1
FLAG_DOCUMENT_14                                     1
FLAG_DOCUMENT_15                                     1
FLAG_DOCUMENT_16                                     1
FLAG_DOCUMENT_17                                     1
FLAG_DOCUMENT_18                                     1
FLAG_DOCUMENT_19                                     1
FLAG_DOCUMENT_20                                     1
FLAG_DOCUMENT_21                                     1
AMT_REQ_CREDIT_BUREAU_HOUR                           1
AMT_REQ_CREDIT_BUREAU_DAY                            1
AMT_REQ_CREDIT_BUREAU_WEEK                           1
AMT_REQ_CREDIT_BUREAU_MON                            1
AMT_REQ_CREDIT_BUREAU_QRT                            1
AMT_REQ_CREDIT_BUREAU_YEAR                           1
AVG_CC_BALANCE                                       1
MAX_CC_BALANCE                                       1
MIN_CC_BALANCE                                       1
MED_CC_BALANCE                                       1
MAX_CC_DPD                                           1
MIN_CC_DPD                                           1
AVG_CC_DPD                                           1
ZERO_CC_DPD                                          1
max_df_POS                                           1
min_df_POS                                           1
mean_df_POS                                          1
percentage_no_DPD_df_POS                             1
NUM_INSTALMENT_NUMBER_pay                            1
DPD_max_pay                                          1
DPD_min_pay                                          1
DPD_avg_pay                                          1
DPD_Count_pay                                        1
AMT_INSTALMENT_pay                                   1
AMT_PAYMENT_pay                                      1
PERCENT_NOT_PAID_pay                                 1
OWED_pay                                             1
PERCENT_UNDER_PAID_pay                               1
PERCENT_OWED_pay                                     1
no_DPD_Percentage_pay                                1
Percent_BU_CREDIT_ACTIVE                             1
COUNT_BU_CREDIT_ACTIVE                               1
AVG_BU_DAYS_CREDIT                                   1
MAX_BU_CREDIT_DAY_OVERDUE                            1
MIN_BU_CREDIT_DAY_OVERDUE                            1
AVG_BU_CREDIT_DAY_OVERDUE                            1
percent_BU_CREDIT_DAY_OVERDUE                        1
MAX_BU_DAYS_CREDIT_ENDDATE                           1
MAX_BU_DAYS_ENDDATE                                  1
AVG_BU_CNT_CREDIT_PROLONG                            1
MAX_BU_CNT_CREDIT_PROLONG                            1
SUM_BU_AMT_CREDIT_SUM                                1
COUNT_BU_CREDIT_TYPE                                 1
MAX_BU_PERCENT_SUM_OVERDUE                           1
AVG_BU_PERCENT_SUM_OVERDUE                           1
AMT_APPLICATION                                      1
NUM_APPLICATIONS                                     1
AMT_APPROVED                                         1
PCT_APPROVED                                         1
MIN_DAYS_DECISION                                    1
PCT_APPL_ON_SAME_DAY                                 1
min_term                                             1
max_term                                             1
mean_term                                            1
DAYS_TERMINATION                                     1
NAME_TYPE_SUITE_Children                             1
NAME_TYPE_SUITE_Family                               1
NAME_TYPE_SUITE_Group of people                      1
NAME_TYPE_SUITE_Other_A                              1
NAME_TYPE_SUITE_Other_B                              1
NAME_TYPE_SUITE_Spouse, partner                      1
NAME_TYPE_SUITE_Unaccompanied                        1
NAME_INCOME_TYPE_Commercial associate                1
NAME_INCOME_TYPE_Maternity leave                     1
NAME_INCOME_TYPE_Pensioner                           1
NAME_INCOME_TYPE_State servant                       1
NAME_INCOME_TYPE_Student                             1
NAME_INCOME_TYPE_Unemployed                          1
NAME_INCOME_TYPE_Working                             1
NAME_EDUCATION_TYPE_Academic degree                  1
NAME_EDUCATION_TYPE_Higher education                 1
NAME_EDUCATION_TYPE_Incomplete higher                1
NAME_EDUCATION_TYPE_Lower secondary                  1
NAME_EDUCATION_TYPE_Secondary / secondary special    1
NAME_FAMILY_STATUS_Civil marriage                    1
NAME_FAMILY_STATUS_Married                           1
NAME_FAMILY_STATUS_Separated                         1
NAME_FAMILY_STATUS_Single / not married              1
NAME_FAMILY_STATUS_Widow                             1
NAME_HOUSING_TYPE_Co-op apartment                    1
NAME_HOUSING_TYPE_House / apartment                  1
NAME_HOUSING_TYPE_Municipal apartment                1
NAME_HOUSING_TYPE_Office apartment                   1
NAME_HOUSING_TYPE_Rented apartment                   1
NAME_HOUSING_TYPE_With parents                       1
OCCUPATION_TYPE_Accountants                          1
OCCUPATION_TYPE_Cleaning staff                       1
OCCUPATION_TYPE_Cooking staff                        1
OCCUPATION_TYPE_Core staff                           1
OCCUPATION_TYPE_Drivers                              1
OCCUPATION_TYPE_HR staff                             1
OCCUPATION_TYPE_High skill tech staff                1
OCCUPATION_TYPE_IT staff                             1
OCCUPATION_TYPE_Laborers                             1
OCCUPATION_TYPE_Low-skill Laborers                   1
OCCUPATION_TYPE_Managers                             1
OCCUPATION_TYPE_Medicine staff                       1
OCCUPATION_TYPE_Private service staff                1
OCCUPATION_TYPE_Realty agents                        1
OCCUPATION_TYPE_Sales staff                          1
OCCUPATION_TYPE_Secretaries                          1
OCCUPATION_TYPE_Security staff                       1
OCCUPATION_TYPE_Unemployed                           1
OCCUPATION_TYPE_Waiters/barmen staff                 1
WEEKDAY_APPR_PROCESS_START_FRIDAY                    1
WEEKDAY_APPR_PROCESS_START_MONDAY                    1
WEEKDAY_APPR_PROCESS_START_SATURDAY                  1
WEEKDAY_APPR_PROCESS_START_SUNDAY                    1
WEEKDAY_APPR_PROCESS_START_THURSDAY                  1
WEEKDAY_APPR_PROCESS_START_TUESDAY                   1
WEEKDAY_APPR_PROCESS_START_WEDNESDAY                 1
ORGANIZATION_TYPE_Advertising                        1
ORGANIZATION_TYPE_Agriculture                        1
ORGANIZATION_TYPE_Bank                               1
ORGANIZATION_TYPE_Business Entity Type 1             1
ORGANIZATION_TYPE_Business Entity Type 2             1
ORGANIZATION_TYPE_Business Entity Type 3             1
ORGANIZATION_TYPE_Cleaning                           1
ORGANIZATION_TYPE_Construction                       1
ORGANIZATION_TYPE_Culture                            1
ORGANIZATION_TYPE_Electricity                        1
ORGANIZATION_TYPE_Emergency                          1
ORGANIZATION_TYPE_Government                         1
ORGANIZATION_TYPE_Hotel                              1
ORGANIZATION_TYPE_Housing                            1
ORGANIZATION_TYPE_Industry: type 1                   1
ORGANIZATION_TYPE_Industry: type 10                  1
ORGANIZATION_TYPE_Industry: type 11                  1
ORGANIZATION_TYPE_Industry: type 12                  1
ORGANIZATION_TYPE_Industry: type 13                  1
ORGANIZATION_TYPE_Industry: type 2                   1
ORGANIZATION_TYPE_Industry: type 3                   1
ORGANIZATION_TYPE_Industry: type 4                   1
ORGANIZATION_TYPE_Industry: type 5                   1
ORGANIZATION_TYPE_Industry: type 6                   1
ORGANIZATION_TYPE_Industry: type 7                   1
ORGANIZATION_TYPE_Industry: type 8                   1
ORGANIZATION_TYPE_Industry: type 9                   1
ORGANIZATION_TYPE_Insurance                          1
ORGANIZATION_TYPE_Kindergarten                       1
ORGANIZATION_TYPE_Legal Services                     1
ORGANIZATION_TYPE_Medicine                           1
ORGANIZATION_TYPE_Military                           1
ORGANIZATION_TYPE_Mobile                             1
ORGANIZATION_TYPE_Other                              1
ORGANIZATION_TYPE_Police                             1
ORGANIZATION_TYPE_Postal                             1
ORGANIZATION_TYPE_Realtor                            1
ORGANIZATION_TYPE_Religion                           1
ORGANIZATION_TYPE_Restaurant                         1
ORGANIZATION_TYPE_Retired                            1
ORGANIZATION_TYPE_School                             1
ORGANIZATION_TYPE_Security                           1
ORGANIZATION_TYPE_Security Ministries                1
ORGANIZATION_TYPE_Self-employed                      1
ORGANIZATION_TYPE_Services                           1
ORGANIZATION_TYPE_Telecom                            1
ORGANIZATION_TYPE_Trade: type 1                      1
ORGANIZATION_TYPE_Trade: type 2                      1
ORGANIZATION_TYPE_Trade: type 3                      1
ORGANIZATION_TYPE_Trade: type 4                      1
ORGANIZATION_TYPE_Trade: type 5                      1
ORGANIZATION_TYPE_Trade: type 6                      1
ORGANIZATION_TYPE_Trade: type 7                      1
ORGANIZATION_TYPE_Transport: type 1                  1
ORGANIZATION_TYPE_Transport: type 2                  1
ORGANIZATION_TYPE_Transport: type 3                  1
ORGANIZATION_TYPE_Transport: type 4                  1
ORGANIZATION_TYPE_University                         1
FONDKAPREMONT_MODE_not specified                     1
FONDKAPREMONT_MODE_org spec account                  1
FONDKAPREMONT_MODE_reg oper account                  1
FONDKAPREMONT_MODE_reg oper spec account             1
HOUSETYPE_MODE_block of flats                        1
HOUSETYPE_MODE_specific housing                      1
HOUSETYPE_MODE_terraced house                        1
WALLSMATERIAL_MODE_Block                             1
WALLSMATERIAL_MODE_Mixed                             1
WALLSMATERIAL_MODE_Monolithic                        1
WALLSMATERIAL_MODE_Others                            1
WALLSMATERIAL_MODE_Panel                             1
WALLSMATERIAL_MODE_Stone, brick                      1
WALLSMATERIAL_MODE_Wooden                            1
REGION_RATING_CLIENT_1                               1
REGION_RATING_CLIENT_2                               1
REGION_RATING_CLIENT_3                               1
REGION_RATING_CLIENT_W_CITY_1                        1
REGION_RATING_CLIENT_W_CITY_2                        1
REGION_RATING_CLIENT_W_CITY_3                        1
dtype: int64

In [45]:
from imblearn.over_sampling import SMOTENC
smt = SMOTENC(categorical_features=cat_col_index,random_state = 11)
X_train_nona1, y_train = smt.fit_sample(X_train_nona, y_train)

# https://medium.com/@saeedAR/smote-and-near-miss-in-python-machine-learning-in-imbalanced-datasets-b7976d9a7a79
# we're using SMOTENC as we have both categorical and continous predictors

In [46]:
print(X_train_nona1.shape, y_train.shape)
print(len(y_train[y_train == 0])/len(y_train))

(452182, 259) (452182,)
0.5

In [47]:
X_train_nona2 = pd.DataFrame(X_train_nona1, columns=X_train_nona.columns)
y_train = pd.Series(y_train)

In [108]:
# save the SMOTED dataset to csv as it takes awhile to run; if any previous dataset is needed, can rerun the steps
X_train_nona2.to_csv(r'cleaned_tables\processed_X_train_SMOTENC.csv', index = True, header = True)
y_train.to_csv(r'cleaned_tables\processed_y_train.csv', index = True, header = False)
X_test_nona.to_csv(r'cleaned_tables\processed_X_test.csv', index = True, header = True)
y_test.to_csv(r'cleaned_tables\processed_y_test.csv', index = True, header = False)